# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16f4d1c44681ba4a65b7e51e48eb311439a973014f15eab11e03e8fd09610d23479442af1ca1161eb5f799614b57e3f87843cad5e44d77b74cb1640095d6ea21

test:
  secret_key_base: 96572a0c95cef031c5d49a1e077a2f1ff77df23f16b0982aeca05a11d225069b3659c6af21801c6ffbf5ac28bf6a192c4bdda409e2fe16d83a5578744f9d4f4f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
